// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String diagnosa;
String fase_gait;
String status_otot;
float beda_sudut;
int emg_val;

void initProperties(){

  ArduinoCloud.addProperty(diagnosa, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fase_gait, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(status_otot, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(beda_sudut, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emg_val, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
